### ISSUE TITLE
Inconsistency of the initial channel number of the generator for LSUN Church.

### ISSUE THREAD

**Issue by lmxyy** [NVlabs/denoising-diffusion-gan#2]
Thanks for this wonderful work. I wonder what is the initial channel number of the generator for LSUN Church. In the paper, it is 128 in Table 6. While in the README, it is set to 64.

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/10475754/161891644-51a3b39c-5bea-4865-978e-c92cdd56d2e7.png">

<img width="863" alt="image" src="https://user-images.githubusercontent.com/10475754/161891690-03a295b2-a600-496c-b64b-39d8cf329971.png">

**Comment by arash-vahdat** [comment]
Thanks Muyang for bringing this to our attention. I can confirm that the channel size for LSUN church should be 64 (as provided in the command). We will fix Table 6 in the paper in our next version.

Thanks!
