### ISSUE TITLE
Can this model's generation be controlled?

### ISSUE THREAD

**Issue by mrakgr** [NVlabs/denoising-diffusion-gan#9]
https://youtu.be/XCUlnHP1TNM?t=3305

This talks about how diffusion models can be used to do class conditional generation, inpainting and colorization. Can the diffusion GAN be used for that as well? Personally, I am interested in style transfer, could the model do that as well?

**Comment by JCBrouwer** [comment]
It's theoretically possible to do these tasks, but it would require quite a few changes to the training scheme and would probably be quite a lot of work.

Luckily for style transfer, though, the unconditional model already suffices!

The input to the model is an image of pure Gaussian noise: `im = torch.randn(1, 3, 256, 256)`

However, you can also just input an image and scale it to look like Gaussian noise:
```py
im = to_tensor(resize(PIL.Image.open(filename), 256)).unsqueeze(0)
im -= im.mean()
im /= im.std()
```

To add a content-style tradeoff you can add extra noise to the image:
```py
style_weight = 5
im = (im + torch.randn_like(im) * style_weight) / (1 + style_weight)
```

You can see an example where I've applied the above to a video [here](https://twitter.com/wavefunk_/status/1513856457455898629).

**Comment by mrakgr** [comment]
I see. I think for my purpose I'd really want to be able to pass along a target style image like in the deep dream generator, rather than have it be random. 

Thank you for answering my questions, I'll keep this area of ML in mind.

**Comment by ghost** [comment]
Hi. Could you please guide me on how to do inpainting with this model too?

**Comment by CanberkSaglam** [comment]
> It's theoretically possible to do these tasks, but it would require quite a few changes to the training scheme and would probably be quite a lot of work.
> 
> Luckily for style transfer, though, the unconditional model already suffices!
> 
> The input to the model is an image of pure Gaussian noise: `im = torch.randn(1, 3, 256, 256)`
> 
> However, you can also just input an image and scale it to look like Gaussian noise:
> 
> ```python
> im = to_tensor(resize(PIL.Image.open(filename), 256)).unsqueeze(0)
> im -= im.mean()
> im /= im.std()
> ```
> 
> To add a content-style tradeoff you can add extra noise to the image:
> 
> ```python
> style_weight = 5
> im = (im + torch.randn_like(im) * style_weight) / (1 + style_weight)
> ```
> 
> You can see an example where I've applied the above to a video [here](https://twitter.com/wavefunk_/status/1513856457455898629).

Could you elaborate on "quite a few changes to the training scheme and would probably be quite a lot of work" a little more? Could you briefly explain what changes need to be made on the training scheme? Thanks for your time.

**Comment by JCBrouwer** [comment]
Well first off, the model would need to get the conditioning information somehow. This would require adjusting the architecture to add the conditional inputs into the both the generator and discriminator. For class conditioned generation that would probably be a class embedding and some MLPs/AdaGroupNorm per layer of the networks. For inpainting or colorization the conditioning is an image, so you'd probably add some kind of convolutional/res-net layer to integrate those inputs at each layer of the networks.

Then the data loading code would need to be changed to also load in/pre-process the correct conditioning for each of the samples in the training set. Then the training script would need to be adjusted to supply the conditioning to the forward method of both the generator and discriminator.

Finally, the inference script would need to be updated to allow specifying/loading in the conditioning information and then supplying it to the forward method of the generator during sampling.

It's all relatively straightforward from a deep learning point of view (there's a lot of prior work on conditional GANs), but will definitely take a bit of elbow-grease and quite some training capacity to test/evaluate correctly.
